/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EtudiantRouteImport } from './routes/etudiant'
import { Route as EcoleRouteImport } from './routes/ecole'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EtudiantIndexRouteImport } from './routes/etudiant.index'
import { Route as EcoleIndexRouteImport } from './routes/ecole.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EtudiantProfilRouteImport } from './routes/etudiant.profil'
import { Route as EtudiantPaiementsRouteImport } from './routes/etudiant.paiements'
import { Route as EtudiantMessagerieRouteImport } from './routes/etudiant.messagerie'
import { Route as EtudiantDossierRouteImport } from './routes/etudiant.dossier'
import { Route as EtudiantDocumentsRouteImport } from './routes/etudiant.documents'
import { Route as EtudiantCursusRouteImport } from './routes/etudiant.cursus'
import { Route as EtudiantBourseRouteImport } from './routes/etudiant.bourse'
import { Route as EcoleRapportsRouteImport } from './routes/ecole.rapports'
import { Route as EcolePaiementsRouteImport } from './routes/ecole.paiements'
import { Route as EcoleMessagerieRouteImport } from './routes/ecole.messagerie'
import { Route as EcoleConventionsRouteImport } from './routes/ecole.conventions'
import { Route as EcoleBoursiersRouteImport } from './routes/ecole.boursiers'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthMfaRouteImport } from './routes/auth.mfa'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AdminUtilisateursRouteImport } from './routes/admin.utilisateurs'
import { Route as AdminReportingRouteImport } from './routes/admin.reporting'
import { Route as AdminParametresRouteImport } from './routes/admin.parametres'
import { Route as AdminPaiementsRouteImport } from './routes/admin.paiements'
import { Route as AdminMessagerieRouteImport } from './routes/admin.messagerie'
import { Route as AdminEtudiantsRouteImport } from './routes/admin.etudiants'
import { Route as AdminEtablissementsRouteImport } from './routes/admin.etablissements'
import { Route as AdminDocumentsRouteImport } from './routes/admin.documents'
import { Route as AdminCandidaturesRouteImport } from './routes/admin.candidatures'
import { Route as AdminBoursesRouteImport } from './routes/admin.bourses'
import { Route as AdminEtudiantsIdRouteImport } from './routes/admin.etudiants.$id'
import { Route as AdminCandidaturesIdRouteImport } from './routes/admin.candidatures.$id'

const EtudiantRoute = EtudiantRouteImport.update({
  id: '/etudiant',
  path: '/etudiant',
  getParentRoute: () => rootRouteImport,
} as any)
const EcoleRoute = EcoleRouteImport.update({
  id: '/ecole',
  path: '/ecole',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EtudiantIndexRoute = EtudiantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EtudiantRoute,
} as any)
const EcoleIndexRoute = EcoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EcoleRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EtudiantProfilRoute = EtudiantProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => EtudiantRoute,
} as any)
const EtudiantPaiementsRoute = EtudiantPaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => EtudiantRoute,
} as any)
const EtudiantMessagerieRoute = EtudiantMessagerieRouteImport.update({
  id: '/messagerie',
  path: '/messagerie',
  getParentRoute: () => EtudiantRoute,
} as any)
const EtudiantDossierRoute = EtudiantDossierRouteImport.update({
  id: '/dossier',
  path: '/dossier',
  getParentRoute: () => EtudiantRoute,
} as any)
const EtudiantDocumentsRoute = EtudiantDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => EtudiantRoute,
} as any)
const EtudiantCursusRoute = EtudiantCursusRouteImport.update({
  id: '/cursus',
  path: '/cursus',
  getParentRoute: () => EtudiantRoute,
} as any)
const EtudiantBourseRoute = EtudiantBourseRouteImport.update({
  id: '/bourse',
  path: '/bourse',
  getParentRoute: () => EtudiantRoute,
} as any)
const EcoleRapportsRoute = EcoleRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => EcoleRoute,
} as any)
const EcolePaiementsRoute = EcolePaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => EcoleRoute,
} as any)
const EcoleMessagerieRoute = EcoleMessagerieRouteImport.update({
  id: '/messagerie',
  path: '/messagerie',
  getParentRoute: () => EcoleRoute,
} as any)
const EcoleConventionsRoute = EcoleConventionsRouteImport.update({
  id: '/conventions',
  path: '/conventions',
  getParentRoute: () => EcoleRoute,
} as any)
const EcoleBoursiersRoute = EcoleBoursiersRouteImport.update({
  id: '/boursiers',
  path: '/boursiers',
  getParentRoute: () => EcoleRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMfaRoute = AuthMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AdminUtilisateursRoute = AdminUtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportingRoute = AdminReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParametresRoute = AdminParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaiementsRoute = AdminPaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagerieRoute = AdminMessagerieRouteImport.update({
  id: '/messagerie',
  path: '/messagerie',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEtudiantsRoute = AdminEtudiantsRouteImport.update({
  id: '/etudiants',
  path: '/etudiants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEtablissementsRoute = AdminEtablissementsRouteImport.update({
  id: '/etablissements',
  path: '/etablissements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCandidaturesRoute = AdminCandidaturesRouteImport.update({
  id: '/candidatures',
  path: '/candidatures',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBoursesRoute = AdminBoursesRouteImport.update({
  id: '/bourses',
  path: '/bourses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEtudiantsIdRoute = AdminEtudiantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminEtudiantsRoute,
} as any)
const AdminCandidaturesIdRoute = AdminCandidaturesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCandidaturesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/ecole': typeof EcoleRouteWithChildren
  '/etudiant': typeof EtudiantRouteWithChildren
  '/admin/bourses': typeof AdminBoursesRoute
  '/admin/candidatures': typeof AdminCandidaturesRouteWithChildren
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/etablissements': typeof AdminEtablissementsRoute
  '/admin/etudiants': typeof AdminEtudiantsRouteWithChildren
  '/admin/messagerie': typeof AdminMessagerieRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/reporting': typeof AdminReportingRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/ecole/boursiers': typeof EcoleBoursiersRoute
  '/ecole/conventions': typeof EcoleConventionsRoute
  '/ecole/messagerie': typeof EcoleMessagerieRoute
  '/ecole/paiements': typeof EcolePaiementsRoute
  '/ecole/rapports': typeof EcoleRapportsRoute
  '/etudiant/bourse': typeof EtudiantBourseRoute
  '/etudiant/cursus': typeof EtudiantCursusRoute
  '/etudiant/documents': typeof EtudiantDocumentsRoute
  '/etudiant/dossier': typeof EtudiantDossierRoute
  '/etudiant/messagerie': typeof EtudiantMessagerieRoute
  '/etudiant/paiements': typeof EtudiantPaiementsRoute
  '/etudiant/profil': typeof EtudiantProfilRoute
  '/admin/': typeof AdminIndexRoute
  '/ecole/': typeof EcoleIndexRoute
  '/etudiant/': typeof EtudiantIndexRoute
  '/admin/candidatures/$id': typeof AdminCandidaturesIdRoute
  '/admin/etudiants/$id': typeof AdminEtudiantsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/admin/bourses': typeof AdminBoursesRoute
  '/admin/candidatures': typeof AdminCandidaturesRouteWithChildren
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/etablissements': typeof AdminEtablissementsRoute
  '/admin/etudiants': typeof AdminEtudiantsRouteWithChildren
  '/admin/messagerie': typeof AdminMessagerieRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/reporting': typeof AdminReportingRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/ecole/boursiers': typeof EcoleBoursiersRoute
  '/ecole/conventions': typeof EcoleConventionsRoute
  '/ecole/messagerie': typeof EcoleMessagerieRoute
  '/ecole/paiements': typeof EcolePaiementsRoute
  '/ecole/rapports': typeof EcoleRapportsRoute
  '/etudiant/bourse': typeof EtudiantBourseRoute
  '/etudiant/cursus': typeof EtudiantCursusRoute
  '/etudiant/documents': typeof EtudiantDocumentsRoute
  '/etudiant/dossier': typeof EtudiantDossierRoute
  '/etudiant/messagerie': typeof EtudiantMessagerieRoute
  '/etudiant/paiements': typeof EtudiantPaiementsRoute
  '/etudiant/profil': typeof EtudiantProfilRoute
  '/admin': typeof AdminIndexRoute
  '/ecole': typeof EcoleIndexRoute
  '/etudiant': typeof EtudiantIndexRoute
  '/admin/candidatures/$id': typeof AdminCandidaturesIdRoute
  '/admin/etudiants/$id': typeof AdminEtudiantsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/ecole': typeof EcoleRouteWithChildren
  '/etudiant': typeof EtudiantRouteWithChildren
  '/admin/bourses': typeof AdminBoursesRoute
  '/admin/candidatures': typeof AdminCandidaturesRouteWithChildren
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/etablissements': typeof AdminEtablissementsRoute
  '/admin/etudiants': typeof AdminEtudiantsRouteWithChildren
  '/admin/messagerie': typeof AdminMessagerieRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/reporting': typeof AdminReportingRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/ecole/boursiers': typeof EcoleBoursiersRoute
  '/ecole/conventions': typeof EcoleConventionsRoute
  '/ecole/messagerie': typeof EcoleMessagerieRoute
  '/ecole/paiements': typeof EcolePaiementsRoute
  '/ecole/rapports': typeof EcoleRapportsRoute
  '/etudiant/bourse': typeof EtudiantBourseRoute
  '/etudiant/cursus': typeof EtudiantCursusRoute
  '/etudiant/documents': typeof EtudiantDocumentsRoute
  '/etudiant/dossier': typeof EtudiantDossierRoute
  '/etudiant/messagerie': typeof EtudiantMessagerieRoute
  '/etudiant/paiements': typeof EtudiantPaiementsRoute
  '/etudiant/profil': typeof EtudiantProfilRoute
  '/admin/': typeof AdminIndexRoute
  '/ecole/': typeof EcoleIndexRoute
  '/etudiant/': typeof EtudiantIndexRoute
  '/admin/candidatures/$id': typeof AdminCandidaturesIdRoute
  '/admin/etudiants/$id': typeof AdminEtudiantsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/ecole'
    | '/etudiant'
    | '/admin/bourses'
    | '/admin/candidatures'
    | '/admin/documents'
    | '/admin/etablissements'
    | '/admin/etudiants'
    | '/admin/messagerie'
    | '/admin/paiements'
    | '/admin/parametres'
    | '/admin/reporting'
    | '/admin/utilisateurs'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth/register'
    | '/auth/reset'
    | '/ecole/boursiers'
    | '/ecole/conventions'
    | '/ecole/messagerie'
    | '/ecole/paiements'
    | '/ecole/rapports'
    | '/etudiant/bourse'
    | '/etudiant/cursus'
    | '/etudiant/documents'
    | '/etudiant/dossier'
    | '/etudiant/messagerie'
    | '/etudiant/paiements'
    | '/etudiant/profil'
    | '/admin/'
    | '/ecole/'
    | '/etudiant/'
    | '/admin/candidatures/$id'
    | '/admin/etudiants/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/bourses'
    | '/admin/candidatures'
    | '/admin/documents'
    | '/admin/etablissements'
    | '/admin/etudiants'
    | '/admin/messagerie'
    | '/admin/paiements'
    | '/admin/parametres'
    | '/admin/reporting'
    | '/admin/utilisateurs'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth/register'
    | '/auth/reset'
    | '/ecole/boursiers'
    | '/ecole/conventions'
    | '/ecole/messagerie'
    | '/ecole/paiements'
    | '/ecole/rapports'
    | '/etudiant/bourse'
    | '/etudiant/cursus'
    | '/etudiant/documents'
    | '/etudiant/dossier'
    | '/etudiant/messagerie'
    | '/etudiant/paiements'
    | '/etudiant/profil'
    | '/admin'
    | '/ecole'
    | '/etudiant'
    | '/admin/candidatures/$id'
    | '/admin/etudiants/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/ecole'
    | '/etudiant'
    | '/admin/bourses'
    | '/admin/candidatures'
    | '/admin/documents'
    | '/admin/etablissements'
    | '/admin/etudiants'
    | '/admin/messagerie'
    | '/admin/paiements'
    | '/admin/parametres'
    | '/admin/reporting'
    | '/admin/utilisateurs'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth/register'
    | '/auth/reset'
    | '/ecole/boursiers'
    | '/ecole/conventions'
    | '/ecole/messagerie'
    | '/ecole/paiements'
    | '/ecole/rapports'
    | '/etudiant/bourse'
    | '/etudiant/cursus'
    | '/etudiant/documents'
    | '/etudiant/dossier'
    | '/etudiant/messagerie'
    | '/etudiant/paiements'
    | '/etudiant/profil'
    | '/admin/'
    | '/ecole/'
    | '/etudiant/'
    | '/admin/candidatures/$id'
    | '/admin/etudiants/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  EcoleRoute: typeof EcoleRouteWithChildren
  EtudiantRoute: typeof EtudiantRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/etudiant': {
      id: '/etudiant'
      path: '/etudiant'
      fullPath: '/etudiant'
      preLoaderRoute: typeof EtudiantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecole': {
      id: '/ecole'
      path: '/ecole'
      fullPath: '/ecole'
      preLoaderRoute: typeof EcoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etudiant/': {
      id: '/etudiant/'
      path: '/'
      fullPath: '/etudiant/'
      preLoaderRoute: typeof EtudiantIndexRouteImport
      parentRoute: typeof EtudiantRoute
    }
    '/ecole/': {
      id: '/ecole/'
      path: '/'
      fullPath: '/ecole/'
      preLoaderRoute: typeof EcoleIndexRouteImport
      parentRoute: typeof EcoleRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/etudiant/profil': {
      id: '/etudiant/profil'
      path: '/profil'
      fullPath: '/etudiant/profil'
      preLoaderRoute: typeof EtudiantProfilRouteImport
      parentRoute: typeof EtudiantRoute
    }
    '/etudiant/paiements': {
      id: '/etudiant/paiements'
      path: '/paiements'
      fullPath: '/etudiant/paiements'
      preLoaderRoute: typeof EtudiantPaiementsRouteImport
      parentRoute: typeof EtudiantRoute
    }
    '/etudiant/messagerie': {
      id: '/etudiant/messagerie'
      path: '/messagerie'
      fullPath: '/etudiant/messagerie'
      preLoaderRoute: typeof EtudiantMessagerieRouteImport
      parentRoute: typeof EtudiantRoute
    }
    '/etudiant/dossier': {
      id: '/etudiant/dossier'
      path: '/dossier'
      fullPath: '/etudiant/dossier'
      preLoaderRoute: typeof EtudiantDossierRouteImport
      parentRoute: typeof EtudiantRoute
    }
    '/etudiant/documents': {
      id: '/etudiant/documents'
      path: '/documents'
      fullPath: '/etudiant/documents'
      preLoaderRoute: typeof EtudiantDocumentsRouteImport
      parentRoute: typeof EtudiantRoute
    }
    '/etudiant/cursus': {
      id: '/etudiant/cursus'
      path: '/cursus'
      fullPath: '/etudiant/cursus'
      preLoaderRoute: typeof EtudiantCursusRouteImport
      parentRoute: typeof EtudiantRoute
    }
    '/etudiant/bourse': {
      id: '/etudiant/bourse'
      path: '/bourse'
      fullPath: '/etudiant/bourse'
      preLoaderRoute: typeof EtudiantBourseRouteImport
      parentRoute: typeof EtudiantRoute
    }
    '/ecole/rapports': {
      id: '/ecole/rapports'
      path: '/rapports'
      fullPath: '/ecole/rapports'
      preLoaderRoute: typeof EcoleRapportsRouteImport
      parentRoute: typeof EcoleRoute
    }
    '/ecole/paiements': {
      id: '/ecole/paiements'
      path: '/paiements'
      fullPath: '/ecole/paiements'
      preLoaderRoute: typeof EcolePaiementsRouteImport
      parentRoute: typeof EcoleRoute
    }
    '/ecole/messagerie': {
      id: '/ecole/messagerie'
      path: '/messagerie'
      fullPath: '/ecole/messagerie'
      preLoaderRoute: typeof EcoleMessagerieRouteImport
      parentRoute: typeof EcoleRoute
    }
    '/ecole/conventions': {
      id: '/ecole/conventions'
      path: '/conventions'
      fullPath: '/ecole/conventions'
      preLoaderRoute: typeof EcoleConventionsRouteImport
      parentRoute: typeof EcoleRoute
    }
    '/ecole/boursiers': {
      id: '/ecole/boursiers'
      path: '/boursiers'
      fullPath: '/ecole/boursiers'
      preLoaderRoute: typeof EcoleBoursiersRouteImport
      parentRoute: typeof EcoleRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/mfa': {
      id: '/auth/mfa'
      path: '/mfa'
      fullPath: '/auth/mfa'
      preLoaderRoute: typeof AuthMfaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/utilisateurs': {
      id: '/admin/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AdminUtilisateursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reporting': {
      id: '/admin/reporting'
      path: '/reporting'
      fullPath: '/admin/reporting'
      preLoaderRoute: typeof AdminReportingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parametres': {
      id: '/admin/parametres'
      path: '/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AdminParametresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paiements': {
      id: '/admin/paiements'
      path: '/paiements'
      fullPath: '/admin/paiements'
      preLoaderRoute: typeof AdminPaiementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messagerie': {
      id: '/admin/messagerie'
      path: '/messagerie'
      fullPath: '/admin/messagerie'
      preLoaderRoute: typeof AdminMessagerieRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/etudiants': {
      id: '/admin/etudiants'
      path: '/etudiants'
      fullPath: '/admin/etudiants'
      preLoaderRoute: typeof AdminEtudiantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/etablissements': {
      id: '/admin/etablissements'
      path: '/etablissements'
      fullPath: '/admin/etablissements'
      preLoaderRoute: typeof AdminEtablissementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/candidatures': {
      id: '/admin/candidatures'
      path: '/candidatures'
      fullPath: '/admin/candidatures'
      preLoaderRoute: typeof AdminCandidaturesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bourses': {
      id: '/admin/bourses'
      path: '/bourses'
      fullPath: '/admin/bourses'
      preLoaderRoute: typeof AdminBoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/etudiants/$id': {
      id: '/admin/etudiants/$id'
      path: '/$id'
      fullPath: '/admin/etudiants/$id'
      preLoaderRoute: typeof AdminEtudiantsIdRouteImport
      parentRoute: typeof AdminEtudiantsRoute
    }
    '/admin/candidatures/$id': {
      id: '/admin/candidatures/$id'
      path: '/$id'
      fullPath: '/admin/candidatures/$id'
      preLoaderRoute: typeof AdminCandidaturesIdRouteImport
      parentRoute: typeof AdminCandidaturesRoute
    }
  }
}

interface AdminCandidaturesRouteChildren {
  AdminCandidaturesIdRoute: typeof AdminCandidaturesIdRoute
}

const AdminCandidaturesRouteChildren: AdminCandidaturesRouteChildren = {
  AdminCandidaturesIdRoute: AdminCandidaturesIdRoute,
}

const AdminCandidaturesRouteWithChildren =
  AdminCandidaturesRoute._addFileChildren(AdminCandidaturesRouteChildren)

interface AdminEtudiantsRouteChildren {
  AdminEtudiantsIdRoute: typeof AdminEtudiantsIdRoute
}

const AdminEtudiantsRouteChildren: AdminEtudiantsRouteChildren = {
  AdminEtudiantsIdRoute: AdminEtudiantsIdRoute,
}

const AdminEtudiantsRouteWithChildren = AdminEtudiantsRoute._addFileChildren(
  AdminEtudiantsRouteChildren,
)

interface AdminRouteChildren {
  AdminBoursesRoute: typeof AdminBoursesRoute
  AdminCandidaturesRoute: typeof AdminCandidaturesRouteWithChildren
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminEtablissementsRoute: typeof AdminEtablissementsRoute
  AdminEtudiantsRoute: typeof AdminEtudiantsRouteWithChildren
  AdminMessagerieRoute: typeof AdminMessagerieRoute
  AdminPaiementsRoute: typeof AdminPaiementsRoute
  AdminParametresRoute: typeof AdminParametresRoute
  AdminReportingRoute: typeof AdminReportingRoute
  AdminUtilisateursRoute: typeof AdminUtilisateursRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBoursesRoute: AdminBoursesRoute,
  AdminCandidaturesRoute: AdminCandidaturesRouteWithChildren,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminEtablissementsRoute: AdminEtablissementsRoute,
  AdminEtudiantsRoute: AdminEtudiantsRouteWithChildren,
  AdminMessagerieRoute: AdminMessagerieRoute,
  AdminPaiementsRoute: AdminPaiementsRoute,
  AdminParametresRoute: AdminParametresRoute,
  AdminReportingRoute: AdminReportingRoute,
  AdminUtilisateursRoute: AdminUtilisateursRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthMfaRoute: typeof AuthMfaRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetRoute: typeof AuthResetRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthMfaRoute: AuthMfaRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetRoute: AuthResetRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface EcoleRouteChildren {
  EcoleBoursiersRoute: typeof EcoleBoursiersRoute
  EcoleConventionsRoute: typeof EcoleConventionsRoute
  EcoleMessagerieRoute: typeof EcoleMessagerieRoute
  EcolePaiementsRoute: typeof EcolePaiementsRoute
  EcoleRapportsRoute: typeof EcoleRapportsRoute
  EcoleIndexRoute: typeof EcoleIndexRoute
}

const EcoleRouteChildren: EcoleRouteChildren = {
  EcoleBoursiersRoute: EcoleBoursiersRoute,
  EcoleConventionsRoute: EcoleConventionsRoute,
  EcoleMessagerieRoute: EcoleMessagerieRoute,
  EcolePaiementsRoute: EcolePaiementsRoute,
  EcoleRapportsRoute: EcoleRapportsRoute,
  EcoleIndexRoute: EcoleIndexRoute,
}

const EcoleRouteWithChildren = EcoleRoute._addFileChildren(EcoleRouteChildren)

interface EtudiantRouteChildren {
  EtudiantBourseRoute: typeof EtudiantBourseRoute
  EtudiantCursusRoute: typeof EtudiantCursusRoute
  EtudiantDocumentsRoute: typeof EtudiantDocumentsRoute
  EtudiantDossierRoute: typeof EtudiantDossierRoute
  EtudiantMessagerieRoute: typeof EtudiantMessagerieRoute
  EtudiantPaiementsRoute: typeof EtudiantPaiementsRoute
  EtudiantProfilRoute: typeof EtudiantProfilRoute
  EtudiantIndexRoute: typeof EtudiantIndexRoute
}

const EtudiantRouteChildren: EtudiantRouteChildren = {
  EtudiantBourseRoute: EtudiantBourseRoute,
  EtudiantCursusRoute: EtudiantCursusRoute,
  EtudiantDocumentsRoute: EtudiantDocumentsRoute,
  EtudiantDossierRoute: EtudiantDossierRoute,
  EtudiantMessagerieRoute: EtudiantMessagerieRoute,
  EtudiantPaiementsRoute: EtudiantPaiementsRoute,
  EtudiantProfilRoute: EtudiantProfilRoute,
  EtudiantIndexRoute: EtudiantIndexRoute,
}

const EtudiantRouteWithChildren = EtudiantRoute._addFileChildren(
  EtudiantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  EcoleRoute: EcoleRouteWithChildren,
  EtudiantRoute: EtudiantRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
